name: 'Generate Changelog using github-changelog-generator'
description: 'Creates or updates a changelog file in your repository with the help of the github-changelog-generator project'
branding:
  icon: 'book-open'
  color: 'green'
inputs:
  options:
    description: 'https://github.com/github-changelog-generator/github-changelog-generator/wiki/Advanced-change-log-generation-examples#additional-options'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.options }}
